// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy/snell/config.proto

package snell

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	protocol "github.com/xtls/xray-core/common/protocol"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_b37284eba0e26ab5, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ClientConfig struct {
	Server               []*protocol.ServerEndpoint `protobuf:"bytes,1,rep,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClientConfig) Reset()         { *m = ClientConfig{} }
func (m *ClientConfig) String() string { return proto.CompactTextString(m) }
func (*ClientConfig) ProtoMessage()    {}
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_b37284eba0e26ab5, []int{1}
}

func (m *ClientConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConfig.Unmarshal(m, b)
}
func (m *ClientConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConfig.Marshal(b, m, deterministic)
}
func (m *ClientConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConfig.Merge(m, src)
}
func (m *ClientConfig) XXX_Size() int {
	return xxx_messageInfo_ClientConfig.Size(m)
}
func (m *ClientConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConfig proto.InternalMessageInfo

func (m *ClientConfig) GetServer() []*protocol.ServerEndpoint {
	if m != nil {
		return m.Server
	}
	return nil
}

type ServerConfig struct {
	User                 *protocol.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ServerConfig) Reset()         { *m = ServerConfig{} }
func (m *ServerConfig) String() string { return proto.CompactTextString(m) }
func (*ServerConfig) ProtoMessage()    {}
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_b37284eba0e26ab5, []int{2}
}

func (m *ServerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerConfig.Unmarshal(m, b)
}
func (m *ServerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerConfig.Marshal(b, m, deterministic)
}
func (m *ServerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerConfig.Merge(m, src)
}
func (m *ServerConfig) XXX_Size() int {
	return xxx_messageInfo_ServerConfig.Size(m)
}
func (m *ServerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ServerConfig proto.InternalMessageInfo

func (m *ServerConfig) GetUser() *protocol.User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "xray.proxy.snell.Account")
	proto.RegisterType((*ClientConfig)(nil), "xray.proxy.snell.ClientConfig")
	proto.RegisterType((*ServerConfig)(nil), "xray.proxy.snell.ServerConfig")
}

func init() {
	proto.RegisterFile("proxy/snell/config.proto", fileDescriptor_b37284eba0e26ab5)
}

var fileDescriptor_b37284eba0e26ab5 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x59, 0x95, 0xaa, 0x69, 0x0f, 0x65, 0xf1, 0xb0, 0xe4, 0x54, 0x17, 0x0b, 0xbd, 0x98,
	0x40, 0xbd, 0x8a, 0xa0, 0xc5, 0x9b, 0x87, 0xb2, 0x45, 0x10, 0x2f, 0xd2, 0xa6, 0xb1, 0x2e, 0x64,
	0x33, 0x61, 0x92, 0xd5, 0xed, 0x2b, 0xf9, 0x94, 0x92, 0x49, 0x15, 0x29, 0x3d, 0x26, 0xdf, 0xef,
	0xfb, 0xc3, 0xb0, 0xc2, 0x21, 0x74, 0x5b, 0xe9, 0xad, 0x36, 0x46, 0x2a, 0xb0, 0xef, 0xf5, 0x46,
	0x38, 0x84, 0x00, 0xf9, 0xb0, 0xc3, 0xe5, 0x56, 0x90, 0x2c, 0x48, 0xe6, 0x5c, 0x41, 0xd3, 0x80,
	0x95, 0xa4, 0x2b, 0x30, 0xb2, 0xf5, 0x1a, 0x13, 0xcd, 0x2f, 0xf7, 0x35, 0xaf, 0xf1, 0x53, 0xe3,
	0x9b, 0x77, 0x5a, 0x25, 0xa4, 0x1c, 0xb3, 0xd3, 0x7b, 0xa5, 0xa0, 0xb5, 0x21, 0xe7, 0xec, 0xcc,
	0x2d, 0xbd, 0xff, 0x02, 0x5c, 0x17, 0xd9, 0x28, 0x9b, 0x9c, 0x57, 0x7f, 0xef, 0xf2, 0x89, 0x0d,
	0x66, 0xa6, 0xd6, 0x36, 0xcc, 0x68, 0x4d, 0x7e, 0xcb, 0x7a, 0x29, 0xab, 0xc8, 0x46, 0xc7, 0x93,
	0xfe, 0xf4, 0x4a, 0xd0, 0xb0, 0xd4, 0x27, 0x7e, 0xfb, 0xc4, 0x82, 0x98, 0x47, 0xbb, 0x76, 0x50,
	0xdb, 0x50, 0xed, 0x3c, 0xe5, 0x1d, 0x1b, 0x24, 0x65, 0x97, 0x26, 0xd8, 0x49, 0x5c, 0x4d, 0xad,
	0xfd, 0x29, 0x3f, 0x9c, 0xf5, 0xec, 0x35, 0x56, 0xc4, 0x3d, 0x54, 0xec, 0x42, 0x41, 0x23, 0xf6,
	0x6f, 0x31, 0xcf, 0x5e, 0xc7, 0x9b, 0x3a, 0x7c, 0xb4, 0xab, 0x68, 0x96, 0x5d, 0x30, 0x5e, 0x46,
	0xe6, 0x5a, 0x01, 0x6a, 0xf9, 0xef, 0xa6, 0xdf, 0x47, 0xc3, 0x97, 0xe8, 0x9d, 0x93, 0x77, 0x11,
	0xbf, 0x56, 0x3d, 0x2a, 0xba, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x62, 0xd7, 0x0e, 0x7c,
	0x01, 0x00, 0x00,
}
