// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy/shadowsocks/config.proto

package shadowsocks

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	net "github.com/xtls/xray-core/common/net"
	protocol "github.com/xtls/xray-core/common/protocol"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CipherType int32

const (
	CipherType_UNKNOWN            CipherType = 0
	CipherType_RC4_MD5_6          CipherType = 1
	CipherType_RC4_MD5            CipherType = 2
	CipherType_SM4_128_CFB        CipherType = 3
	CipherType_AES_128_CFB        CipherType = 4
	CipherType_AES_256_CFB        CipherType = 5
	CipherType_CHACHA20           CipherType = 6
	CipherType_CHACHA20_IETF      CipherType = 7
	CipherType_SM4_128_GCM        CipherType = 8
	CipherType_AES_128_GCM        CipherType = 9
	CipherType_AES_256_GCM        CipherType = 10
	CipherType_CHACHA20_POLY1305  CipherType = 11
	CipherType_XCHACHA20_POLY1305 CipherType = 12
	CipherType_NONE               CipherType = 13
)

var CipherType_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "RC4_MD5_6",
	2:  "RC4_MD5",
	3:  "SM4_128_CFB",
	4:  "AES_128_CFB",
	5:  "AES_256_CFB",
	6:  "CHACHA20",
	7:  "CHACHA20_IETF",
	8:  "SM4_128_GCM",
	9:  "AES_128_GCM",
	10: "AES_256_GCM",
	11: "CHACHA20_POLY1305",
	12: "XCHACHA20_POLY1305",
	13: "NONE",
}

var CipherType_value = map[string]int32{
	"UNKNOWN":            0,
	"RC4_MD5_6":          1,
	"RC4_MD5":            2,
	"SM4_128_CFB":        3,
	"AES_128_CFB":        4,
	"AES_256_CFB":        5,
	"CHACHA20":           6,
	"CHACHA20_IETF":      7,
	"SM4_128_GCM":        8,
	"AES_128_GCM":        9,
	"AES_256_GCM":        10,
	"CHACHA20_POLY1305":  11,
	"XCHACHA20_POLY1305": 12,
	"NONE":               13,
}

func (x CipherType) String() string {
	return proto.EnumName(CipherType_name, int32(x))
}

func (CipherType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1da88f084d5cf23f, []int{0}
}

type Account struct {
	Password             string     `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	CipherType           CipherType `protobuf:"varint,2,opt,name=cipher_type,json=cipherType,proto3,enum=xray.proxy.shadowsocks.CipherType" json:"cipher_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_1da88f084d5cf23f, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetCipherType() CipherType {
	if m != nil {
		return m.CipherType
	}
	return CipherType_UNKNOWN
}

type ServerConfig struct {
	Users                []*protocol.User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Network              []net.Network    `protobuf:"varint,2,rep,packed,name=network,proto3,enum=xray.common.net.Network" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ServerConfig) Reset()         { *m = ServerConfig{} }
func (m *ServerConfig) String() string { return proto.CompactTextString(m) }
func (*ServerConfig) ProtoMessage()    {}
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1da88f084d5cf23f, []int{1}
}

func (m *ServerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerConfig.Unmarshal(m, b)
}
func (m *ServerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerConfig.Marshal(b, m, deterministic)
}
func (m *ServerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerConfig.Merge(m, src)
}
func (m *ServerConfig) XXX_Size() int {
	return xxx_messageInfo_ServerConfig.Size(m)
}
func (m *ServerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ServerConfig proto.InternalMessageInfo

func (m *ServerConfig) GetUsers() []*protocol.User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ServerConfig) GetNetwork() []net.Network {
	if m != nil {
		return m.Network
	}
	return nil
}

type ClientConfig struct {
	Server               []*protocol.ServerEndpoint `protobuf:"bytes,1,rep,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClientConfig) Reset()         { *m = ClientConfig{} }
func (m *ClientConfig) String() string { return proto.CompactTextString(m) }
func (*ClientConfig) ProtoMessage()    {}
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1da88f084d5cf23f, []int{2}
}

func (m *ClientConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConfig.Unmarshal(m, b)
}
func (m *ClientConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConfig.Marshal(b, m, deterministic)
}
func (m *ClientConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConfig.Merge(m, src)
}
func (m *ClientConfig) XXX_Size() int {
	return xxx_messageInfo_ClientConfig.Size(m)
}
func (m *ClientConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConfig proto.InternalMessageInfo

func (m *ClientConfig) GetServer() []*protocol.ServerEndpoint {
	if m != nil {
		return m.Server
	}
	return nil
}

func init() {
	proto.RegisterEnum("xray.proxy.shadowsocks.CipherType", CipherType_name, CipherType_value)
	proto.RegisterType((*Account)(nil), "xray.proxy.shadowsocks.Account")
	proto.RegisterType((*ServerConfig)(nil), "xray.proxy.shadowsocks.ServerConfig")
	proto.RegisterType((*ClientConfig)(nil), "xray.proxy.shadowsocks.ClientConfig")
}

func init() {
	proto.RegisterFile("proxy/shadowsocks/config.proto", fileDescriptor_1da88f084d5cf23f)
}

var fileDescriptor_1da88f084d5cf23f = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xad, 0x21, 0xe1, 0x63, 0x80, 0x74, 0xb3, 0x52, 0x91, 0xe5, 0x43, 0x45, 0x51, 0x0f, 0xa8,
	0x55, 0x6d, 0xe2, 0x84, 0xa8, 0x87, 0x5e, 0xc8, 0x96, 0x34, 0x55, 0x83, 0x41, 0x26, 0x51, 0xd3,
	0x5e, 0x2c, 0xb2, 0x6c, 0x83, 0x1b, 0xe2, 0xb5, 0x76, 0x97, 0x02, 0x7f, 0xa9, 0xff, 0xaf, 0xf7,
	0x6a, 0x6d, 0x43, 0x68, 0x93, 0x1c, 0x90, 0x98, 0xf7, 0xde, 0xbc, 0x79, 0x33, 0x5e, 0x78, 0x19,
	0x0b, 0xbe, 0x5c, 0x39, 0x72, 0x3a, 0x9e, 0xf0, 0x85, 0xe4, 0xf4, 0x56, 0x3a, 0x94, 0x47, 0x3f,
	0xc2, 0x1b, 0x3b, 0x16, 0x5c, 0x71, 0x5c, 0x5f, 0x8a, 0xf1, 0xca, 0x4e, 0x44, 0xf6, 0x96, 0xc8,
	0x32, 0x29, 0xbf, 0xbb, 0xe3, 0x91, 0x13, 0x31, 0xa5, 0x7f, 0x0b, 0x2e, 0x6e, 0xd3, 0x0e, 0xcb,
	0xca, 0x98, 0xa4, 0xa2, 0x7c, 0xe6, 0xcc, 0x25, 0x13, 0x19, 0xf7, 0xea, 0x7f, 0x4e, 0x32, 0xf1,
	0x8b, 0x89, 0x40, 0xc6, 0x8c, 0xa6, 0x92, 0xe6, 0x4f, 0x28, 0x76, 0x29, 0xe5, 0xf3, 0x48, 0x61,
	0x0b, 0x4a, 0xf1, 0x58, 0xca, 0x05, 0x17, 0x13, 0xd3, 0x68, 0x18, 0xad, 0xb2, 0xbf, 0xa9, 0x31,
	0x81, 0x0a, 0x0d, 0xe3, 0x29, 0x13, 0x81, 0x5a, 0xc5, 0xcc, 0xcc, 0x35, 0x8c, 0xd6, 0x9e, 0xdb,
	0xb4, 0x1f, 0x4f, 0x6b, 0x93, 0x44, 0x7a, 0xb1, 0x8a, 0x99, 0x0f, 0x74, 0xf3, 0xbf, 0xa9, 0xa0,
	0x3a, 0x4a, 0x02, 0x90, 0x64, 0x65, 0xdc, 0x86, 0x5d, 0x1d, 0x56, 0x9a, 0x46, 0x23, 0xdf, 0xaa,
	0xb8, 0x56, 0x6a, 0x97, 0x66, 0xb6, 0xd7, 0x99, 0xed, 0x4b, 0xc9, 0x84, 0x9f, 0x0a, 0xb1, 0x0b,
	0xc5, 0x6c, 0x7b, 0x33, 0xd7, 0xc8, 0xb7, 0xf6, 0x5c, 0xf3, 0x9f, 0x9e, 0x88, 0x29, 0xdb, 0x4b,
	0x79, 0x7f, 0x2d, 0x6c, 0x9e, 0x43, 0x95, 0xcc, 0x42, 0x16, 0xa9, 0x6c, 0xea, 0x07, 0x28, 0xa4,
	0x67, 0xc8, 0xc6, 0xbe, 0x7e, 0x7c, 0x6c, 0x9a, 0xb4, 0x17, 0x4d, 0x62, 0x1e, 0x46, 0xca, 0xcf,
	0x7a, 0xde, 0xfc, 0x31, 0x00, 0xee, 0xd7, 0xc3, 0x15, 0x28, 0x5e, 0x7a, 0x5f, 0xbc, 0xc1, 0x57,
	0x0f, 0x3d, 0xc3, 0x35, 0x28, 0xfb, 0xe4, 0x28, 0xe8, 0x7f, 0xec, 0x04, 0xc7, 0xc8, 0xd0, 0x5c,
	0x56, 0xa2, 0x1c, 0x7e, 0x0e, 0x95, 0x51, 0xff, 0x28, 0x38, 0x70, 0xdf, 0x07, 0xe4, 0xf4, 0x04,
	0xe5, 0x35, 0xd0, 0xed, 0x8d, 0x36, 0xc0, 0xce, 0x1a, 0x70, 0x3b, 0xc7, 0x09, 0xb0, 0x8b, 0xab,
	0x50, 0x22, 0x67, 0x5d, 0x72, 0xd6, 0x75, 0xdb, 0xa8, 0x80, 0xf7, 0xa1, 0xb6, 0xae, 0x82, 0xcf,
	0xbd, 0x8b, 0x53, 0x54, 0xdc, 0xf6, 0xfc, 0x44, 0xfa, 0xa8, 0xb4, 0xed, 0xa9, 0x81, 0xf2, 0xb6,
	0xa7, 0x06, 0x00, 0xbf, 0x80, 0xfd, 0x8d, 0xcb, 0x70, 0x70, 0xfe, 0xed, 0xe0, 0xb0, 0xdd, 0x41,
	0x15, 0x5c, 0x07, 0x7c, 0xf5, 0x10, 0xaf, 0xe2, 0x12, 0xec, 0x78, 0x03, 0xaf, 0x87, 0x6a, 0x27,
	0x13, 0xd0, 0x0f, 0xed, 0x89, 0x0f, 0x3e, 0x34, 0xbe, 0xbf, 0xbd, 0x09, 0xd5, 0x74, 0x7e, 0xad,
	0xcf, 0xe8, 0x2c, 0xd5, 0x4c, 0x3a, 0x5a, 0xf9, 0x8e, 0x72, 0xc1, 0x9c, 0x07, 0x4f, 0xfe, 0x77,
	0xae, 0x7e, 0xa5, 0x7d, 0x86, 0x89, 0xcf, 0xe8, 0x9e, 0xb8, 0x2e, 0x24, 0xe7, 0x3f, 0xfc, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0x9d, 0xb4, 0xd6, 0x98, 0x27, 0x03, 0x00, 0x00,
}
