// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transport/internet/websocket/config.proto

package websocket

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6b613a5653ee16, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Header) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Config struct {
	// URL path to the WebSocket service. Empty value means root(/).
	Path                string    `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Header              []*Header `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty"`
	AcceptProxyProtocol bool      `protobuf:"varint,4,opt,name=accept_proxy_protocol,json=acceptProxyProtocol,proto3" json:"accept_proxy_protocol,omitempty"`
	// enable mux
	Mux                  bool     `protobuf:"varint,5,opt,name=mux,proto3" json:"mux,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea6b613a5653ee16, []int{1}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Config) GetHeader() []*Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Config) GetAcceptProxyProtocol() bool {
	if m != nil {
		return m.AcceptProxyProtocol
	}
	return false
}

func (m *Config) GetMux() bool {
	if m != nil {
		return m.Mux
	}
	return false
}

func init() {
	proto.RegisterType((*Header)(nil), "xray.transport.internet.websocket.Header")
	proto.RegisterType((*Config)(nil), "xray.transport.internet.websocket.Config")
}

func init() {
	proto.RegisterFile("transport/internet/websocket/config.proto", fileDescriptor_ea6b613a5653ee16)
}

var fileDescriptor_ea6b613a5653ee16 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x49, 0xdb, 0x95, 0x19, 0x2f, 0x23, 0x2a, 0xf4, 0xd8, 0x0d, 0x84, 0xee, 0x60, 0x22,
	0x13, 0xbc, 0xab, 0x17, 0xf5, 0x54, 0x8a, 0xa0, 0x78, 0x19, 0x69, 0x8c, 0x6b, 0x59, 0xdb, 0x84,
	0x34, 0xd5, 0xf6, 0x03, 0xf8, 0x65, 0xf4, 0x4b, 0x4a, 0xd2, 0x3f, 0xc7, 0xed, 0xf6, 0x24, 0xcf,
	0xef, 0x7d, 0xf2, 0xbc, 0x81, 0x6b, 0xad, 0x68, 0x55, 0x4b, 0xa1, 0x34, 0xc9, 0x2b, 0xcd, 0x55,
	0xc5, 0x35, 0xf9, 0xe6, 0x69, 0x2d, 0xd8, 0x9e, 0x6b, 0xc2, 0x44, 0xf5, 0x99, 0xef, 0xb0, 0x54,
	0x42, 0x0b, 0xb4, 0x6c, 0x15, 0xed, 0xf0, 0xc4, 0xe3, 0x91, 0xc7, 0x13, 0xbf, 0xba, 0x86, 0xfe,
	0x23, 0xa7, 0x1f, 0x5c, 0xa1, 0x05, 0x74, 0xf7, 0xbc, 0x0b, 0x40, 0x08, 0xa2, 0x93, 0xc4, 0x48,
	0x74, 0x0e, 0x67, 0x5f, 0xb4, 0x68, 0x78, 0xe0, 0xd8, 0xbb, 0xfe, 0xb0, 0xfa, 0x03, 0xd0, 0x7f,
	0xb0, 0xaf, 0x20, 0x04, 0x3d, 0x49, 0x75, 0x36, 0xf8, 0x56, 0xa3, 0x3b, 0xe8, 0x67, 0x36, 0x30,
	0x70, 0x43, 0x37, 0x3a, 0xdd, 0xac, 0xf1, 0xd1, 0x12, 0xb8, 0x6f, 0x90, 0x0c, 0x83, 0x68, 0x03,
	0x2f, 0x28, 0x63, 0x5c, 0xea, 0xad, 0x54, 0xa2, 0xed, 0xb6, 0x76, 0x19, 0x26, 0x8a, 0xc0, 0x0b,
	0x41, 0x34, 0x4f, 0xce, 0x7a, 0x33, 0x36, 0x5e, 0x3c, 0x58, 0xa6, 0x7d, 0xd9, 0xb4, 0xc1, 0xcc,
	0x12, 0x46, 0x3e, 0x7b, 0x73, 0xb0, 0x70, 0xee, 0x7f, 0x00, 0xbc, 0x64, 0xa2, 0x3c, 0x5e, 0x22,
	0x06, 0xef, 0xb7, 0xbb, 0x5c, 0x67, 0x4d, 0x8a, 0x99, 0x28, 0x49, 0xab, 0x8b, 0x9a, 0x98, 0xa1,
	0x2b, 0x26, 0x14, 0x27, 0x87, 0xfe, 0xfc, 0xd7, 0x59, 0xbe, 0x99, 0xf4, 0x97, 0x29, 0xfd, 0x69,
	0x4c, 0x7f, 0x1d, 0x99, 0xd4, 0xb7, 0x4b, 0xdc, 0xfc, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xaf,
	0xac, 0xcc, 0xbe, 0x01, 0x00, 0x00,
}
